In [176]:
import os
import pandas as pd
import numpy as np
from glob import glob

In [178]:
csv_list = glob("entrerios_test/*.csv")

In [180]:
df = pd.read_csv(csv_list[0], skiprows=1)

In [182]:
csv_list

['entrerios_test\\01  N1  Amelia Riquelme - planilla para evaluaciones.xlsx - Planilla.csv',
 'entrerios_test\\02 N1 Cecilia Ramírez - planilla para evaluaciones - Planilla.csv',
 'entrerios_test\\03 N1 Gloria Briozzo - planilla para evaluaciones - Planilla.csv',
 'entrerios_test\\04 N1 Luisina Vergara - planilla para evaluaciones - Planilla.csv',
 'entrerios_test\\05 N1 María Laura Farias - planilla para evaluaciones - Planilla.csv',
 'entrerios_test\\06 N1 Patricia Lencina- planilla para evaluaciones - Planilla.csv',
 'entrerios_test\\07 N1 Samanta Stablun planilla para evaluaciones - Planilla.csv',
 'entrerios_test\\10 N2 Celeste Danhel - planilla para evaluaciones - Planilla.csv',
 'entrerios_test\\11 N2 Laura Bertrán - planilla para evaluaciones - Planilla.csv',
 'entrerios_test\\12 N2 Adriana Bonin  - planilla para evaluaciones - Planilla.csv',
 'entrerios_test\\13 N2 Diana Esperanza - planilla para evaluaciones - Planilla.csv',
 'entrerios_test\\14 N2  Eugenia Retamozo - planilla para evaluaciones - Planilla (1).csv',
 'entrerios_test\\15 N2 Laura Deruder- planilla para evaluaciones - Planilla (1).csv',
 'entrerios_test\\16 N2 Marina Boero- planilla para evaluaciones - Planilla (1).csv',
 'entrerios_test\\17 N2 Patricia Toniolo- planilla para evaluaciones.xlsx - Planilla.csv',
 'entrerios_test\\18 N2 Mayda Racedo - planilla para evaluaciones - Planilla.csv',
 'entrerios_test\\19 N3 Andrea Soukany - planilla para evaluaciones - Planilla.csv',
 'entrerios_test\\20 N3 Andrea Susan - planilla para evaluaciones - Planilla.csv',
 'entrerios_test\\21 N3 Graciela Blanco - planilla para evaluaciones - Planilla.csv',
 'entrerios_test\\22 N3 Fabiana Tarabini - planilla para evaluaciones - Planilla.csv',
 'entrerios_test\\23 N3 Fátima Arias - planilla para evaluaciones - Planilla.csv',
 'entrerios_test\\24 N3 Katu- planilla para evaluaciones - Planilla.csv',
 'entrerios_test\\25 N3 Lia Soutus - planilla para evaluaciones - Planilla.csv',
 'entrerios_test\\26 N3 Maria Laura Ferreyra - planilla para evaluaciones - Planilla.csv',
 'entrerios_test\\27 N3 Monica Morot - planilla para evaluaciones - Planilla.csv',
 'entrerios_test\\28 N3 Nuria González - planilla para evaluaciones - Planilla.csv',
 'entrerios_test\\29 N2 Eladia Vello -  planilla para evaluaciones - Planilla.csv',
 'entrerios_test\\30 N3 Sandra Suleski - planilla para evaluaciones - Planilla.csv',
 'entrerios_test\\31 N3 Silvia Boaglio - planilla para evaluaciones - Planilla.csv',
 'entrerios_test\\32 N3 Silvia Bustos - planilla para evaluaciones - Planilla.csv',
 'entrerios_test\\33 N3 Valeria Capurro - planilla para evaluaciones - Planilla.csv',
 'entrerios_test\\34 N3 Yanina Lamanna - planilla para evaluaciones - Planilla.csv',
 'entrerios_test\\35 N4 Claudia Grasmück  - planilla para evaluaciones - Planilla.csv',
 'entrerios_test\\36 N4 Daiana Virginio - planilla para evaluaciones - Planilla.csv',
 'entrerios_test\\37 N4 Fabiola Milden  Entre Ríos - planilla para evaluaciones - Planilla.csv',
 'entrerios_test\\38 N4 Jime Allende - planilla para evaluaciones - Planilla.csv',
 'entrerios_test\\39 N4 Laura Leiva - planilla para evaluaciones - Planilla.csv',
 'entrerios_test\\40 N4 Laura Ojeda - planilla para evaluaciones - Planilla.csv',
 'entrerios_test\\41 Lily Albornoz - planilla para evaluaciones - Planilla.csv',
 'entrerios_test\\42 N4 Romina Leuze - planilla para evaluaciones - Planilla.csv',
 'entrerios_test\\43 N4 Shirley Freri - planilla para evaluaciones - Planilla.csv',
 'entrerios_test\\44 N4 Valeria Casse - planilla para evaluaciones - Planilla.csv']

In [183]:
for csv in csv_list[1:]:
    df_tmp = pd.read_csv(csv, skiprows=1)
    df = pd.concat([df, df_tmp], ignore_index=True)

C:\Users\pamden\AppData\Local\Temp\ipykernel_12940\214259493.py:3: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat([df, df_tmp], ignore_index=True)

In [184]:
# df.PRUEBA.map('{:,.0f}'.format).str.zfill(4)

In [185]:
df.duplicated().sum()

0

In [186]:
df = df.iloc[:, :-1]

In [192]:
column_names = [
    "Código de anonimización",
    "Fecha de nacimiento",
    "Género",
    "Jardín",
    "Sala",
    "version_voc",
    "ID_voc_tablet",
    "ID_voc_prueba",
    "version_conc_fono",
    "ID_conc_fono_tablet",
    "ID_conc_fono_prueba",
    "version_sist_escrit",
    "ID_sist_escrit_tablet",
    "ID_sist_escrit_prueba",
    "Supervisión",
    "localidad",
    "Ocupación de los padres",
    "Comentarios"]
# Renombrar las columnas del DataFrame
df.columns = column_names

In [193]:
df["ID_voc_prueba"] = (
    df["ID_voc_prueba"]
    .fillna(0)  # Opcional: manejar NaN (por ejemplo, reemplazarlos por 0)
    .astype(int)  # Asegurar que los valores son enteros
    .map('{:04d}'.format)  # Formatear con ceros a la izquierda
)
# Convertir a formato numérico y rellenar con ceros (manejo de NaN)
df["ID_conc_fono_prueba"] = (
    df["ID_conc_fono_prueba"]
    .fillna(0)  # Opcional: manejar NaN (por ejemplo, reemplazarlos por 0)
    .astype(int)  # Asegurar que los valores son enteros
    .map('{:04d}'.format)  # Formatear con ceros a la izquierda
)
df["ID_sist_escrit_prueba"] = (
    df["ID_sist_escrit_prueba"]
    .fillna(0)  # Opcional: manejar NaN (por ejemplo, reemplazarlos por 0)
    .astype(int)  # Asegurar que los valores son enteros
    .map('{:04d}'.format)  # Formatear con ceros a la izquierda
)

In [196]:
df["ID_voc_tablet"] = df["ID_voc_tablet"].fillna(0).astype(int)
df["ID_conc_fono_tablet"] = df["ID_conc_fono_tablet"].fillna(0).astype(int)
df["ID_sist_escrit_tablet"] = df["ID_sist_escrit_tablet"].fillna(0).astype(int)

In [199]:
df["ID_voc"] = df["ID_voc_tablet"].astype(str) + "-" + df["ID_voc_prueba"].astype(str)
df["ID_conc_fono"] = df["ID_conc_fono_tablet"].astype(str) + "-" + df["ID_conc_fono_prueba"].astype(str)
df["ID_sist_escrit"] = df["ID_sist_escrit_tablet"].astype(str) + "-" + df["ID_sist_escrit_prueba"].astype(str)
df

,Código de anonimización,Fecha de nacimiento,Género,Jardín,Sala,version_voc,ID_voc_tablet,ID_voc_prueba,version_conc_fono,ID_conc_fono_tablet,...,version_sist_escrit,ID_sist_escrit_tablet,ID_sist_escrit_prueba,Supervisión,localidad,Ocupación de los padres,Comentarios,ID_voc,ID_conc_fono,ID_sist_escrit
0,ER2410101,21/05/2019,Masculino,UENI N 69,SALA 5 AÑOS,A,3853,0008,A,3853,...,A,3853,0012,FELICIANO ZONAXVIII,SAN JOSÉ DE FELICIANO,AMA DE CASA,NaN,3853-0008,3853-0017,3853-0012
1,ER2410102,07/11/2018,Masculino,UENI N 69,SALA 5 AÑOS,A,3853,0012,A,3853,...,A,3853,0012,FELICIANO ZONA XVIII - María Jorgelina Paniagua,SAN JOSÉ DE FELICIANO,AMA DE CASA,NaN,3853-0012,3853-0012,3853-0012
2,ER2410103,19/08/2018,Masculino,UENI N 69,SALA 5 AÑOS,A,3853,0015,A,3853,...,A,3853,0015,FELICIANO ZONA XVIII - María Jorgelina Paniagua,SAN JOSÉ DE FELICIANO,AMA DE CASA,NaN,3853-0015,3853-0015,3853-0015
3,ER2410104,20/09/2018,Masculino,UENI N 69,SALA 5 AÑOS,B,3853,0018,B,3853,...,B,3853,0019,FELICIANO ZONA XVIII - María Jorgelina Paniagua,SAN JOSÉ DE FELICIANO,DOCENTE Y POLICIA,NaN,3853-0018,3853-0020,3853-0019
4,ER2410105,29/11/2018,Masculino,UENI N 69,SALA 5 AÑOS,B,3853,0021,B,3853,...,B,3853,0022,FELICIANO ZONA XVIII - María Jorgelina Paniagua,SAN JOSÉ DE FELICIANO,AMA DE CASA,NaN,3853-0021,3853-0023,3853-0022
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
690,ER2414410,07/03/2019,Masculino,ESC EDU PRIM N 92,5TM,B,4360,0183,B,4360,...,B,4360,0184,URUGUAY ZONA IV - Silvina Daniela Suarez,CONCEPCIÓN DEL URUGUAY,NaN,NaN,4360-0183,4360-0185,4360-0184
691,ER2414411,03/01/2019,Femenino,ESC EDU PRIM N 92,5TM,A,4360,0186,A,4360,...,A,4360,0187,URUGUAY ZONA IV - Silvina Daniela Suarez,CONCEPCIÓN DEL URUGUAY,NaN,NaN,4360-0186,4360-0188,4360-0187
692,ER2414412,21/07/2018,Masculino,ESC EDU PRIM N 3,5TM,A,4360,0190,A,4360,...,A,4360,0191,URUGUAY ZONA IV - Silvina Daniela Suarez,CONCEPCIÓN DEL URUGUAY,NaN,NaN,4360-0190,4360-0192,4360-0191
693,ER2414413,10/08/2018,Femenino,ESC EDU PRIM N 3,5TM,B,4360,0193,B,4360,...,B,4360,0194,URUGUAY ZONA IV - Silvina Daniela Suarez,CONCEPCIÓN DEL URUGUAY,NaN,NaN,4360-0193,4360-0195,4360-0194
694,ER2414414,21/03/2019,Femenino,UENI N 16,5TM,A,6577,0000,A,6577,...,A,6577,0000,URUGUAY ZONA IV - Silvina Daniela Suarez,CONCEPCIÓN DEL URUGUAY,NaN,NaN,6577-0000,6577-0000,6577-0000

In [201]:
df.drop(columns=["ID_voc_tablet", "ID_voc_prueba","ID_conc_fono_tablet",    "ID_conc_fono_prueba",     "ID_sist_escrit_tablet",    "ID_sist_escrit_prueba",    "ID_sist_escrit_prueba"], inplace=True)

In [203]:
df.shape

(695, 15)

In [205]:
df.to_csv("df_entrerios.csv")

In [207]:
df_melted = pd.melt(
    df,
    id_vars=[
        "Código de anonimización",
        "Fecha de nacimiento",
        "Género",
        "Jardín",
        "Sala",
        "version_voc",
        "version_conc_fono",
        "version_sist_escrit",
        "Supervisión",
        "localidad",
        "Ocupación de los padres",
        "Comentarios"
    ],
    value_vars=["ID_sist_escrit", "ID_conc_fono", "ID_voc"],
    var_name="prueba",
    value_name="test_id",
    col_level=None,
    ignore_index=True
)

In [209]:
# Lo uso para descargar la data del server
df_melted["test_id"].to_csv("listado_ids_entrerios.csv")

In [211]:
df_server=pd.read_csv("data_server_entrerios.csv")

In [212]:
valores_faltantes = df_melted[~df_melted["test_id"].isin(df_server["test_id"])]
# valores_faltantes.to_csv("valores_faltantes.csv")